Feature/kundenstimmen
daizugmbh/dawn pull request #13
Opened 2021-07-16 07:10 UTC by sklinkusch

# Implementierung der Kundenstimmen-Section

- Implementierung des Sleepink-Sliders (_infinite loop_)
- unterschiedliche Implementierungen für Mobile/Tablet (1 Spalte) und Desktop (2 Spalten)
- Layout vom Shopify-Slider bzw. der ursprünglichen Section weitestgehend übernommen

## Desktop

![image](https://user-images.githubusercontent.com/42465490/125906726-6e055688-043c-4ce5-bc34-cc1a5c30da97.png)

## Mobil

![image](https://user-images.githubusercontent.com/42465490/125907072-4a16aff1-aba5-4102-8486-742b431b9b92.png)

2021-07-26 12:38 UTC, iliquifysnacks requested changes
- [ ] Die Bilder sollten in 2x Auflösung geladen werden, damit sie auch auf Retina Displays gut aussehen
- [ ] Die Bilder werden im Moment noch mit einem verzerrten Seitenverhältnis angezeigt. Das Frontend sollte auch für nicht quadratische Bilder funktionieren
- [ ] Der Haken neben dem Namen ist noch nicht vertikal mittig aligned
<img width="1385" alt="Screenshot 2021-07-26 at 14 25 15" src="https://user-images.githubusercontent.com/46820607/126988763-1daee808-0e7c-4895-86ab-3c553d6c78c2.png">

- [ ] Bei mir werden nur die ersten zwei Slides angezeigt, die Buttons oder Slide funktioniert noch nicht. Das Problem tritt auf meinem iPhone nicht auf, dort wird die Paginierung korrekt angezeigt und der Slider funktioniert. 
<img width="1478" alt="Screenshot 2021-07-26 at 14 28 17" src="https://user-images.githubusercontent.com/46820607/126988729-c1a47d20-53ae-4fc0-b82b-647fd7e822d5.png">

- [ ] Ich hätte gerne noch die Möglickeit, halbe Sterne zu vergeben
- [ ] Das Spacing zwischen Überschrift und Slides ist vor allem auf Mobile etwas zu großzügig bemessen. Vielleicht probieren wir es mit 50% des aktuellen Wertes?
![IMG_459909734E26-1](https://user-images.githubusercontent.com/46820607/126989857-b0f786d2-184d-4acf-99eb-1a846358f962.jpeg)

2021-07-27 10:23 UTC, sklinkusch commented
Das liegt an der verschiedenen Höhe der Bilder. Ich kann das Avatar und die anderen Angaben eigentlich nur in einen ausreichend hohen Container packen und dort zentrieren. Dann müsste es das gewesen sein.

2021-07-27 12:42 UTC, iliquifysnacks commented
Ich denke auch, dass die vorgeschlagene Anpassung das Problem löst

2021-07-27 12:47 UTC, sklinkusch commented
Der Container mit einer Höhe von 70px, `overflow: hidden;` und Flexbox-Eigenschaften sollte das Problem gelöst haben.

![grafik](https://user-images.githubusercontent.com/42465490/127155932-00388d61-6c09-44ee-8a88-c2c8b8a20edb.png)

2021-07-27 12:58 UTC, iliquifysnacks approved these changes
Sehr gut, so passt es!

2021-07-27 12:58 UTC, merged