Feature/bestseller
daizugmbh/dawn pull request #14
Opened 2021-07-20 07:32 UTC by sklinkusch

# Implementierung einer Bestseller-Section

- Slider auf allen Viewports
- unterschiedliche Grids (mobil: 1 Spalte, Tablet: 2 Spalten, Desktop: 4 Spalten)

2021-07-26 12:55 UTC, iliquifysnacks requested changes
Statt die Details der Produkte händisch einzutragen, sollten wir hier von dem Eingabetyp "product" gebrauch machen, der uns von Shopify zur Verfügung gestellt wird. 

Wir könnten sogar die Option geben, entweder mehrere Produkte oder eine Kollektion zu verlinken, durch welche die section dann mapt. 

<img width="305" alt="Screenshot 2021-07-26 at 14 53 12" src="https://user-images.githubusercontent.com/46820607/126992138-984dd46a-d133-4da0-a119-7c5853307b24.png">

2021-07-27 12:13 UTC, sklinkusch commented
Ich habe, wie bereits angedeutet, alle Produktdaten bis auf Produktauswahl und SKU herausgenommen. Sie werden entweder aus den vorhandenen Produkt- und Variantenobjekten oder aus den Metafields geholt. Desweiteren habe ich dem Desktop-Grid einen Gap von 12px gegeben, weil sonst die Bilder schon ineinander übergingen.

2021-07-27 12:47 UTC, iliquifysnacks reviewed
Aus irgendeinem Grund werden die Artikel bei mir nicht gerendert: 

![Screenshot 2021-07-27 at 14 46 37](https://user-images.githubusercontent.com/46820607/127155975-f5166eeb-1d28-4853-9b5f-fc64ba32668d.png)
![Screenshot 2021-07-27 at 14 47 12](https://user-images.githubusercontent.com/46820607/127155986-165472a7-f2ed-45a3-b1c3-4e53cde5547a.png)

2021-07-27 13:28 UTC, sklinkusch commented
Jetzt wird bei nur einer Variante eines Produkts diese auch ausgewählt, selbst wenn keine SKU angegeben worden ist.

2021-07-28 08:23 UTC, iliquifysnacks commented
Vielen Dank für die Änderungen! Die Produktauswahl ist super, jetzt ist es für die Nutzer deutlich einfacher. Mir sind noch ein paar Unebenheiten visueller Natur aufgefallen: 

- [ ] Der Teil des Buttons, der das Produkt direkt in den Einkaufswagen legt ist etwas kleiner vertikal als der Rest des Buttons
- [ ] Beim Bild der Schlafessenz kann man sehen, dass das Seitenverhältnis durch die Komponente beeinflusst wird. Ich würde vorschlagen, dass Problem mit einem object-fit contain zu lösen. Dann würde das Bild im Zweifel etwas zu klein angezeigt, aber nicht verzerrt. 
<img width="1407" alt="Screenshot 2021-07-28 at 10 01 58" src="https://user-images.githubusercontent.com/46820607/127289000-6c8ddd6b-e11f-4c96-8328-0a11c967eb90.png">

- [ ] Der Slider wird nicht rechtzeitig genutzt bei schmaleren Viewports. Wie auf dem Screenshot zu sehen, wird einfach ein Teil der Produktkachel abgeschnitten.
<img width="1133" alt="Screenshot 2021-07-28 at 10 04 02" src="https://user-images.githubusercontent.com/46820607/127289494-60d946e1-ff5b-4895-b9cd-5f13923b6bab.png">

Ansonsten sieht das alles sehr gut aus.

2021-07-28 08:23 UTC, iliquifysnacks requested changes
Siehe letzten Kommentar

2021-07-28 13:56 UTC, sklinkusch commented
# Bearbeitung des Change Requests

1. **Änderung der Bildgröße**: Die Bildgröße war bislang nur über HTML-Attribute festgelegt. Nun wird sie über CSS determiniert, was sie variabler hinsichtlich der Breite des Viewports macht. Ein Abschneiden des Sliders bei 1200px ist nicht mehr denkbar. Der Breakpoint ist ja auch erst bei 990px.
2. **Änderung des Buttons**: Der ATC-Button wurde so angepasst, dass er analog zu dem Link zur Produktseite eine Höhe von 45px hat. Optisch sieht es manchmal noch so aus, als wäre er kleiner. Doch ich will ihn nicht noch größer machen.
3. **Nutzung der Metafelder**: Die Metafelder konnten bisher nicht genutzt werden, weil sie nicht richtig aufgerufen worden sind. Das ist jetzt korrigiert. Die korrekte Syntax lautet ` {{ section.blocks.settings.product.metafields.global.description }}`

2021-07-29 13:12 UTC, iliquifysnacks approved these changes
Hervorragend! Die Sterne konnte ich grade nicht nutzen, weil meine Metafields nicht richtig definiert sind, aber das sieht sehr gut aus!

2021-07-29 13:14 UTC, merged