Feature/product preview slider
daizugmbh/dawn pull request #17
Opened 2021-07-22 13:20 UTC by sklinkusch

# Teilweise Implementierung des Produktvorschausliders

- Slider mit einem Aussehen wie auf der Netlify-Seite
- Slider ist animiert, wechselt alle 15 Sekunden die Slide
- Slider stoppt **nicht**, wenn die Maus über dem Slider ist

2021-07-27 13:26 UTC, iliquifysnacks requested changes
- [ ] Halbe Sterne aus Kundenstimmen-Section übernehmen
- [ ] Produktbild aus referenziertem Produkt laden, wenn kein Bild angegeben wird 
- [ ] Produktseite aus referenziertem Produkt laden
- [ ] CTA Beschriftung dynamisch machen

2021-07-28 08:55 UTC, iliquifysnacks requested changes
- [ ] Alignment von Bewertungstext und Sternen stimmt noch nicht 100%
<img width="502" alt="Screenshot 2021-07-28 at 10 47 43" src="https://user-images.githubusercontent.com/46820607/127293533-df36d46f-a5be-46fe-893b-87865a7c1ed4.png">

- [ ] Bewertung nur anzeigen, wenn diese in den Metafields gesetzt ist
- [ ] Metafields separat anlegen
- [ ] Steuerelement des Sliders nach rechts verschieben (wie bei den anderen Komponenten auch)
- [ ] Feature Icons werden noch verzerrt, vielleicht auch mit object-fit contain arbeiten

2021-07-29 06:34 UTC, sklinkusch commented
# Bearbeitung des Change Requests

## Alignment von Sternen und Text
Die Sterne wurden um 4px nach unten verschoben, damit sieht es besser aus. 

## Bewertung abhängig von Daten in den Metafields
Die Bewertung samt Text wird nur noch gerendert, wenn es in den Metafields ein rating und einen reviewCount gibt.

## Metafields separat anlegen
Die Metafields sind nicht mehr als JSON-String angelegt, sondern als einzelne Variablen.

## Position des Steuerelements
Die Buttons sind inzwischen auf der rechten Seite der Section.

## Aussehen der Icons
Meines Erachtens sind die Icons nicht mehr verzerrt. Dank ` object-fit: contain;`dürften sie das auch nicht mehr sein. Als Beweis habe ich den Screenshot angehängt. Die Bilder sind doch echt werbewirksam. Vielleicht sollten wir die künftig auch nehmen. 

![grafik](https://user-images.githubusercontent.com/42465490/127443236-a5fcd6cf-c4e2-4e38-b247-dd234f4481bb.png)

2021-08-02 07:20 UTC, iliquifysnacks requested changes
- [ ] Der Abstand zwischen der Liste der Vorteile und dem CTA Button sowie der Abstand zwischen Headline und Liste der Vorteile sollten gleich sein. Dabei sollte der Abstand zwischen Headline und Liste deutlich kleiner werden und der Abststand zwischen Liste und Button etwas größer.
- [ ] Auf Mobile sollten diese Abstände beide kleiner werden.
![IMG_2BD1796B5C61-1](https://user-images.githubusercontent.com/46820607/127820034-79ef01e9-c4cf-459c-8f1b-f3d7c304e62d.jpeg)
<img width="890" alt="Screenshot 2021-08-02 at 09 16 08" src="https://user-images.githubusercontent.com/46820607/127820046-536c0357-9ce0-4057-9061-fcd997d65620.png">

2021-08-02 12:03 UTC, sklinkusch commented
# Bearbeitung des Change Requests

- [X] Abstände der Liste nach oben und nach unten auf 0 reduziert.
- [X] object-fit des Bildes auf cover gesetzt

2021-08-04 12:54 UTC, iliquifysnacks approved these changes
So sieht es für meine Augen alles gut aus!

2021-08-04 12:54 UTC, merged