Hotfix/sticky header
daizugmbh/dawn pull request #27
Opened 2021-08-09 10:59 UTC by sklinkusch

# Beheben des Sticky-Verhaltens beim Menü

## Behobene Fehler

1. ID im Javascript-Code auf das richtige Element gesetzt (Wrapper statt beschrifteter Teil des Menüs)
2. Animation verlängert (0.45s statt 0.15s)
3. Elemente umbenannt (zur Vermeidung von Konflikten mit anderen Elementen)

2021-08-10 11:12 UTC, iliquifysnacks requested changes
- [ ] Die Animation wird bei mir in Firefox nicht angezeigt
- [ ] Rechts und links vom Header ist noch ein drop shadow 
- [ ] Der Text ist noch nicht ganz zentriert auf der vertikalen Achse
![Screenshot 2021-08-10 at 12 54 16](https://user-images.githubusercontent.com/46820607/128857123-51a2f3ab-d34e-492e-ba73-8d6a15b4e886.png)
![Screenshot 2021-08-10 at 12 53 33](https://user-images.githubusercontent.com/46820607/128857140-85769a6b-9645-4a01-a122-28c595adf52b.png)

2021-08-10 12:34 UTC, sklinkusch commented
# Bearbeitung des Change-Requests

- [X] Animation läuft jetzt smoother
- [X] Drop-Shadow wurde entfernt
- [] Text zentrieren

Den Text habe ich mit Absicht nicht zentriert, weil das auch bei unserem Menü nicht der Fall ist. Es gibt in dem Menü drei einzelne Container: einer für das Logo, einer für die Menüpunkte und einer für die Icons rechts. Diese sind mit Flexbox: space-between angeordnet, so dass die Abstände maximiert werden. Der Abstand zwischen Logo und Menü entspricht dem zwischen Menü und Icons. Zentriert ist das Menü nur dann, wenn die Breite des Logos der Breite des Icon-Containers entspricht.

2021-08-11 08:56 UTC, iliquifysnacks requested changes
Bezüglich des zentrierten Textes: Es ging mir darum, dass der Text auf der vertikalen Achse zentriert ist.

2021-08-13 09:28 UTC, iliquifysnacks approved these changes
Jetzt funktioniert alles bei mir :)

2021-08-13 09:28 UTC, merged