Feature/slidable hero
daizugmbh/dawn pull request #49
Opened 2021-11-05 09:33 UTC by sklinkusch

# Implementierung eines automatisierten Sliders für das Hero-Element

- Wechsel alle 15 Sekunden
- Video oder Bild möglich
- Textfarbe kann auf jeder Slide angepasst werden
- Kontrollelemente links und rechts mit verringerter Opacity
- Dots wurden vorbereitet, jedoch nicht vollständig realisiert (Funktion zum Wechsel der Slide wird trotz eines vorhandenen EventListeners nicht ausgeführt)

2022-01-12 10:17 UTC, iliquifysnacks requested changes
- [x] Korrektur von fehlenden Dots und und Pfeilen unter dem Slider über rework auf swiper
- [ ] Button Text auf Mobile nicht zentriert auf der vertikalen Achse
- [ ] "Bekannt aus" Text padding 
- [ ] "Bekannt aus" font-weight bold
- [ ] Toggle für gradient-overlay mobile
- [ ] Gradient overlay für mobile um weiße Presselogos darzustellen

2022-01-13 07:50 UTC, sklinkusch commented
Ich habe die Änderungen wie gewünscht eingebaut.

2022-01-13 09:50 UTC, iliquifysnacks requested changes
- [x] Dots unter Presselogos mobile
- [x] Mobile Pfeile nicht anzeigen
- [ ] Farbschemas intuitiver benennen 
- [ ] Swiper über CDN Link importieren
- [ ] Overlap Buttons / Überschrift verhindern

2022-01-13 11:46 UTC, sklinkusch commented
Die Änderung sind jetzt eingebaut.
Da das Ändern des Swipers auf CDN keine Verbesserung gebracht hat, habe ich jetzt nur das async (ebenso wie defer) im Script-Tag entfernt. Damit erzeuge ich zwar im VSCode-Liquid-Theme-Check einen Fehler, dafür läuft der Import problemlos, sowohl lokal wie auch in der offenen Variante. Du kannst es dir ja ansehen [(https://sleep-ink-dev2.myshopify.com/,](https://sleep-ink-dev2.myshopify.com/) Passwort: iwiart)

2022-01-13 13:03 UTC, sklinkusch commented
Ist er jetzt ja auch.

2022-01-13 14:18 UTC, iliquifysnacks commented
To Dos nach Review mit Koray und Malte

- [ ] VH basierte Höhe der Komponente
- [ ] Pfeile Desktop mit padding 32 zum viewport edge
- [ ] Presselogos etwas höher
- [ ] Padding unter den Presselogos etwas reduzieren

2022-01-14 07:35 UTC, merged